version: '3'
# ==============================================================================
# The HelloWorld SUT.
# ==============================================================================

services:
# Start the Hello World federate
  helloworld:
    image: ivct/helloworld:ma-${HW_VERSION}
    network_mode: host
    environment:
    - SETTINGS_DESIGNATOR=${SETTINGS_DESIGNATOR}
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
