version: '3'
# ==============================================================================
# SHIPSIM SUT composition for the Pitch RTI using HOST NETWORK MODE 
# ==============================================================================

services:
# ==============================================================================
# SHIPSIM SUT composition includes the Pitch CRC and Pitch web UI, plus a
# license container image for the CRC.
# ==============================================================================
  crc:
    image: app-docker136.hex.tno.nl/pitch/crc:5.4.0.0
    depends_on:
    - license
    mac_address: ${MAC_ADDRESS}
    volumes:
    - license_volume:/etc/.java/.systemPrefs/se/pitch/prti1516e/config:nocopy
    ports:
    - "8989:8989"

  web:
    image: app-docker136.hex.tno.nl/pitch/web:2.3.0
    ports:
    - "8181:8080"
   
  license:
    image: ${LICENSE_IMAGE}
    volumes:
    - license_volume:/data
    
# ==============================================================================
# The SHIPSIM SUT
#
# Since the CRC runs on the same host as the SUT, it is addressed as localhost.
# Force the federate application to use the proper network interface (in this
# case eth0) when checking for the network route to the CRC. Otherwise it may
# select the lo interface which causes the LRC to fail later on when it actually
# does want to connect to the CRC.
# ==============================================================================
  shipsim:
    image: app-docker136.hex.tno.nl/msaas-aus/shipsim:pi
    network_mode: host
    environment:
    - FEDERATENAME=SHIPSIM
    - PITCH_LRCADAPTER=eth0
    - PITCH_CRCADDRESS=localhost:8989
    - LRC_MASTERADDRESS=localhost:8989
    depends_on:
    - crc

volumes:
  license_volume:
