version: '3'
# ==============================================================================
# The HelloWorld SUT
# In this composition the SUT connects to the CRC via the Docker host network.
# Ensure that the advertised port range does not overlap with other federates.
# ==============================================================================

services:
# The HW application including the LRC.
# The LRC is mounted from the host file system.
  helloworld:
    image: ivct/helloworld:pi-skeleton-${TS_HW_VERSION}
    environment:
    - PITCH_ADVERTISE_ADDRESS=${DOCKERHOST}:6100:5100
    - SETTINGS_DESIGNATOR=crcAddress=${DOCKERHOST}:8989
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
    ports:
    - "6100:6100/tcp"
    - "5100:5100/udp"
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/lrc/code
