version: '3.7'
# ==============================================================================
# The Pitch CRC composition.
# ==============================================================================

services:
# Start the X Server.
# To connect, navigate to http://$DOCKERHOST:8181/vnc.html
  xserver:
    image: hlacontainers/xserver
    ports:
    - "8181:8080"
    networks:
    - sutnet

# Start the Pitch CRC
# and mount the RTI from the host file system.
  crc:
    image: hlacontainers/pitch-crc:skeleton
    environment:
    - DISPLAY=xserver:0
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/prti1516e
    networks:
    - sutnet

networks:
  sutnet:
    driver: bridge
    name: mysimnetwork
