version: '3'
# ==============================================================================
# IVCT composition for the Portico RTI
# ==============================================================================

services:
# ==============================================================================
# Apache Active Message Queue
# The MQ is used for communication between the different IVCT components.
# ==============================================================================
  activemq:
    image: rmohr/activemq:5.14.5-alpine
    network_mode: host

# ==============================================================================
# IVCT Test Case Runner
# The TC Runner is an HLA federate application based on an LRC base image.
# ==============================================================================
  tc-runner:
    image: ivct/tc-runner:po-development-latest
    network_mode: host
    depends_on:
    - activemq
    - runtime-config
    - ts-hla-encoding-rules
    volumes:
    - runtime-config:/root/conf:nocopy
    - ts-hla-encoding-rules:/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1:nocopy
    environment:
    - IVCT_CONF=/root/conf/

# ==============================================================================
# IVCT Logsink component
# ==============================================================================
  logsink:
    image: ivct/logsink:development-latest
    network_mode: host
    depends_on:
    - activemq
    - runtime-config
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
    - IVCT_CONF=/root/conf/

# ==============================================================================
# IVCT GUI component
# URL: http://${DOCKERHOST}:8080/ivct.gui.ui.html
# Login: admin / admin
# ==============================================================================
  gui:
    image: ivct/ivct-gui:development-latest
    network_mode: host
    depends_on:
    - activemq
    - runtime-config
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
    - IVCT_CONF=/root/conf/

# ==============================================================================
# IVCT runtime configuration data
# ==============================================================================
  runtime-config:
    image: ivct/runtime-config:development-latest
    volumes:
    - runtime-config:/root/conf

# ==============================================================================
# IVCT Test Suite data for Encoding Rules
# ==============================================================================
  ts-hla-encoding-rules:
    image: ivct/ts-hla-encoding-rules:development-1.0.1
    volumes:
    - ts-hla-encoding-rules:/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1

# ==============================================================================
# Data volumes for IVCT Runtime Config data and Test Suite data
# ==============================================================================
volumes:
  runtime-config:
  ts-hla-encoding-rules:
