version: '3'
# ==============================================================================
# The HelloWorld SUT
# In this composition the SUT connects to the CRC via the Docker host network.
# Ensure that the advertised port range does not overlap with other federates.
# ==============================================================================

services:
# The HW application including the LRC.
# The LRC is mounted from the host file system.
  helloworld-a:
    image: ivct/helloworld:pi-skeleton-${TS_HW_VERSION}
    environment:
    # Advertise the LRC port range on which max 10 federates can connect
    # via TCP and UDP.
    - PITCH_ADVERTISE_ADDRESS=${DOCKERHOST}:6200-6209:6210-6219
    - SETTINGS_DESIGNATOR=crcAddress=${DOCKERHOST}:8989
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
    ports:
    - "6200-6209:6200-6209/tcp"
    - "6210-6219:6210-6219/udp"
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/lrc/code
