version: '3'
# ==============================================================================
# SHIPSIM SUT composition for the Pitch RTI
# ==============================================================================

services:
# ==============================================================================
# SHIPSIM SUT composition includes the Pitch CRC and Pitch web UI, plus a
# license container image for the CRC.
# ==============================================================================
  crc:
    image: app-docker136.hex.tno.nl/pitch/crc:5.4.0.0
    depends_on:
    - license
    environment:
    - PITCH_CRCADDRESS=${DOCKERHOST}:8989
    mac_address: ${MAC_ADDRESS}
    volumes:
    - license_volume:/etc/.java/.systemPrefs/se/pitch/prti1516e/config:nocopy
    ports:
    - "8989:8989"

  web:
    image: app-docker136.hex.tno.nl/pitch/web:2.3.0
    ports:
    - "8181:8080"

  license:
    image: ${LICENSE_IMAGE}
    volumes:
    - license_volume:/data

# ==============================================================================
# RTI license
# ==============================================================================
volumes:
  license_volume:
