version: '3'
# ==============================================================================
# The HelloWorld SUT, including the Pitch CRC.
# In this composition the SUT connects to the CRC via the Docker host network.
# The LRC advertises the ports on which it can be contacted by the IVCT and
# other federates.
# Ensure that the advertised port range does not overlap with other federates.
# ==============================================================================

services:
# The X Server.
# To connect, navigate to http://$DOCKERHOST:8181/vnc.html
  xserver:
    image: hlacontainers/xserver
    ports:
    - "8181:8080"

# The Pitch CRC.
# The RTI is mounted from the host file system.
  crc:
    image: hlacontainers/pitch-crc:skeleton
    environment:
    - DISPLAY=xserver:0
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/prti1516e
    ports:
    - "8989:8989"

# The HW application including the LRC.
# The LRC is mounted from the host file system.
  helloworld:
    image: ivct/helloworld:pi-skeleton-${TS_HW_VERSION}
    environment:
    # Advertise the LRC port range on which max 10 federates can connect
    # via TCP and UDP.
    - PITCH_ADVERTISE_ADDRESS=${DOCKERHOST}:6100-6109:6110-6119
    # For the Pitch Free RTI we wait 10 sec for the user to press the Accept button in the CRC UI.
    # After this wait the federate is started and will attempt to connect to the RTI.
    # This will fail if the Accept button has not been pressed by that time.
    - LRC_SLEEPPERIOD=10
    - SETTINGS_DESIGNATOR=crcAddress=${DOCKERHOST}:8989
    - FEDERATE_NAME=A1
    - POPULATION=100
    - CYCLES=1000000
    ports:
    - "6100-6109:6100-6109/tcp"
    - "6110-6119:6110-6119/udp"
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/lrc/code
