version: '3.7'
# ==============================================================================
# The HelloWorld SUT
# ==============================================================================

services:
# The HW application.
# The LRC is mounted from the host file system.
  helloworld_a:
    image: ivct/helloworld:pi-skeleton-${HW_VERSION}
    environment:
    - SETTINGS_DESIGNATOR=crcAddress=${CRC_HOST}:${CRC_PORT}
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/lrc/code
    networks:
    - sutnet

networks:
  sutnet:
    driver: bridge
    name: mysimnetwork
