version: '3'

# ==============================================================================
# HelloWorld IVCT composition
#
# This composition consists of various container images to test the HelloWorld
# federate application.
#
# In this composition the Pitch CRC is started with a license container.
# The license key in the license container is tight to a Pitch license agreement
# and must remain proprietary to the licensee. Therefore the license container
# cannot be stored in the MSaaS Docker Registry. The license container image is
# defined by an environment variable.
# ==============================================================================

services:
# ==============================================================================
# Pitch CRC
# The CRC publishes its port on the Docker Host so that the non-containerized
# federate application "HelloWorld" can connect to the CRC.
# The MAC_ADDRESS is required and the value relates to the license key in the
# licenses container.
# The DISPLAY setting is optional, and, if set, must refer is an X Server
# display.
# ==============================================================================
  crc:
    image: app-docker136.hex.tno.nl/pitch/crc:5.4.0.0
    depends_on:
    - license
    ports:
    - "8989:8989"
    mac_address: ${MAC_ADDRESS}
    environment:
      DISPLAY: ${DISPLAY}
      CRC_REJECT_MISMATCHED_VERSIONS: "false"
      CRC_SKIP_CONNECTIVITY_CHECK: "true"
    volumes:
    - license_volume:/etc/.java/.systemPrefs/se/pitch/prti1516e/config:nocopy

# ==============================================================================
# Pitch CRC license container
# The provided image contains the license key.
# ==============================================================================
  license:
    image: ${LICENSE_IMAGE}
    volumes:
    - license_volume:/license-key
    
# ==============================================================================
# Pitch web UI container
# This image provides a web UI to the CRC.
# URL: ${DOCKERHOST}:${WEBUI_PORT}//webview
# Login: admin / admin
# ==============================================================================
  webui:
    image: app-docker136.hex.tno.nl/pitch/web:2.3.0
    ports:
    - "${WEBUI_PORT}:8080"
      
# ==============================================================================
# Apache Active Message Queue
# Just get this image from the Docker Hub.
# The MQ is used for communication between the different IVCT components.
# The ports are listed for reference, but do not need to be exposed and may be
# omitted.
# ==============================================================================
  activemq:
    image: rmohr/activemq:5.14.5-alpine
    ports:
    - "61616:61616"
    - "8161:8161"

# ==============================================================================
# IVCT Test Case Runner
# The TC Runner is an HLA federate application based on the Pitch LRC base
# image.
# 
# Since the non-containerized federate application "HelloWorld" runs outside
# the VPN of this composition and must be able to connect to the federation,
# it is necessary to expose the LRC ports of the TC Runner to the Docker Host,
# using the PITCH_ADVERTISE_ADDRESS. Both a TCP and a UDP port range are
# exposed for reliable and best effort communication.
# ==============================================================================
  tc-runner:
    image: msg134/tc-runner:development-latest
    depends_on:
    - activemq
    - runtime-config
    - ts-helloworld
    - ts-hla-encoding-rules-tester
    ports:
    - "6100-6109:6100-6109/tcp"
    - "6110-6119:6110-6119/udp"
    volumes:
    - runtime-config:/root/conf:nocopy
    - ts-helloworld:/root/conf/TestSuites/TS_HelloWorld-1.0.0:nocopy
    - ts-hla-encoding-rules-tester:/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.0:nocopy
    environment:
      PITCH_ADVERTISE_ADDRESS: ${DOCKERHOST}:6100-6109:6110-6119
      LRC_MINSLEEP: 10
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/

# ==============================================================================
# IVCT Logsink component
# ==============================================================================
  logsink:
    image: msg134/logsink:development-latest
    depends_on:
    - activemq
    - runtime-config
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/
    
# ==============================================================================
# IVCT GUI component
# ==============================================================================
  gui:
    image: msg134/ivct-gui:development-latest
    depends_on:
    - activemq
    - runtime-config
    ports:
    - "${IVCTUI_PORT}:8080"
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/
      
# ==============================================================================
# IVCT runtime configuration data
# ==============================================================================
  runtime-config:
    image: msg134/runtime-config:development-latest
    volumes:
    - runtime-config:/root/conf

# ==============================================================================
# IVCT Test Suite data for Helloworld
# ==============================================================================
  ts-helloworld:
    image: msg134/ts-helloworld
    volumes:
    - ts-helloworld:/root/conf/TestSuites/TS_HelloWorld-1.0.0
      
# ==============================================================================
# IVCT Test Suite data for Encoding Rules 
# ==============================================================================
  ts-hla-encoding-rules-tester:
    image: msg134/ts-hla-encoding-rules-tester
    volumes:
    - ts-hla-encoding-rules-tester:/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.0

# ==============================================================================
# Data volumes
# ==============================================================================
volumes:
  runtime-config:
  ts-helloworld:
  ts-hla-encoding-rules-tester:
  license_volume:
