version: '3'

# ==============================================================================
# HelloWorld IVCT composition
#
# This composition consists of various container images to test the HelloWorld
# federate application.
#
# In this composition the Pitch CRC is started with a license container.
# The license key in the license container is tight to a Pitch license agreement
# and must remain proprietary to the licensee. Therefore the license container
# cannot be stored in the MSaaS Docker Registry. The container image used is an
# example.
# ==============================================================================

services:
# ==============================================================================
# Pitch CRC
# The CRC publishes its port on the Docker Host so that the non-containerized
# federate application "HelloWorld" can connect to the CRC. The value of
# MAC_ADDRESS is related to the license key in the license container.
# Check the CRC wiki page for more options.
# ==============================================================================
  crc:
    image: app-docker136.hex.tno.nl/pitch/crc:5.4.0.0
    depends_on:
    - license
    ports:
    - "8989:8989"
    mac_address: ${MAC_ADDRESS}
    environment:
      DISPLAY: xserver:0
      CRC_REJECT_MISMATCHED_VERSIONS: "false"
    volumes:
    - license_volume:/etc/.java/.systemPrefs/se/pitch/prti1516e/config:nocopy

# ==============================================================================
# Pitch CRC license container
# The image used here is for example purposes only.
# ==============================================================================
  license:
    image: ${LICENSE_IMAGE}
    volumes:
    - license_volume:/license-key

# ==============================================================================
# General X Server
# The X Server is in this composition used for displaying the Pitch CRC GUI.
# Instead of the X Server the Pitch Web UI can be used also.
# ==============================================================================
  xserver:
    image: app-docker136.hex.tno.nl/library/xserver
    ports:
    - "${XSERVER_PORT}:8080"
      
# ==============================================================================
# Apache Active Message Queue
# Just get this image from the Docker Hub.
# The MQ is used for communication between the different IVCT components.
# ==============================================================================
  activemq:
    image: rmohr/activemq:5.14.5-alpine
    ports:
    - "61616:61616"
    - "8161:8161"

# ==============================================================================
# IVCT Test Case Runner
# The TC Runner is an HLA federate application based on the Pitch LRC base
# image. By default the container waits for the CRC to be up.
# Since the non-containerized federate application "HelloWorld" runs outside the
# VPN of this composition and must be able to connect to the federation, it is
# necessary to publish the LRC ports of this application to the Docker Host,
# using the PITCH_ADVERTISE_ADDRESS. Both a TCP and a UDP port range are
# published for reliable and best effort communication.
# Check the LRC wiki page for more LRC options.
# ==============================================================================
  tc-runner:
    image: ivct/tc-runner:development-latest
    depends_on:
    - activemq
    - runtime-config
    - ts-helloworld
    - ts-hla-encoding-rules-tester
    ports:
    - "6100-6109:6100-6109/tcp"
    - "6110-6119:6110-6119/udp"
    volumes:
    - runtime-config:/root/conf:nocopy
    - ts-helloworld:/root/conf/TestSuites/TS_HelloWorld-1.0.1:nocopy
    - ts-hla-encoding-rules-tester:/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1:nocopy
    environment:
      PITCH_ADVERTISE_ADDRESS: ${DOCKERHOST}:6100-6109:6110-6119
      LRC_MINSLEEP: 10
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/

# ==============================================================================
# IVCT Logsink component
# ==============================================================================
  logsink:
    image: ivct/logsink:development-latest
    depends_on:
    - activemq
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/
    
# ==============================================================================
# IVCT GUI component
# ==============================================================================
  gui:
    image: ivct/ivct-gui:development-latest
    depends_on:
    - activemq
    ports:
    - "${IVCT_GUI}:8080"
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/
      
# ==============================================================================
# IVCT runtime configuration data
# ==============================================================================
  runtime-config:
    image: ivct/runtime-config:development-latest
    volumes:
    - runtime-config:/root/conf

# ==============================================================================
# IVCT Test Suite data for Helloworld
# ==============================================================================
  ts-helloworld:
    image: ivct/ts-helloworld:development-latest
    volumes:
    - ts-helloworld:/root/conf/TestSuites/TS_HelloWorld
      
# ==============================================================================
# IVCT Test Suite data for Encoding Rules 
# ==============================================================================
  ts-hla-encoding-rules-tester:
    image: ivct/ts-hla-encoding-rules:development-latest
    volumes:
    - ts-hla-encoding-rules-tester:/root/conf/TestSuites/TS_HLA_EncodingRulesTester

# ==============================================================================
# Data volumes
# ==============================================================================
volumes:
  runtime-config:
  ts-helloworld:
  ts-hla-encoding-rules-tester:
  license_volume:
