version: '3'
# ==============================================================================
# The Pitch CRC composition.
# ==============================================================================

services:
  xserver:
    image: hlacontainers/xserver
    ports:
    - "8181:8080"

  crc:
    image: hlacontainers/pitch-crc:skeleton
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/prti1516e
    environment:
    - DISPLAY=xserver:0
    ports:
    - "8989:8989"
