version: '3'
# ==============================================================================
# The HelloWorld SUT.
# ==============================================================================

services:
  helloworld:
    image: ivct/helloworld:pi-bare-${TS_HW_VERSION}
    network_mode: host
    environment:
    - PITCH_CRCADDRESS=${PITCH_CRCADDRESS}
    - SETTINGS_DESIGNATOR=${SETTINGS_DESIGNATOR}
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
    volumes:
    - ${PITCH_HOME}/lib:/usr/local/pitch/lib
    - ${PITCH_HOME}/include:/usr/local/pitch/include
    - ${LRC_SETTINGSDIR}:/root/prti1516e
