version: '3'
# ==============================================================================
# The HelloWorld SUT.
# ==============================================================================

services:
# Start the Hello World federate
# and mount the LRC from the host file system.
  helloworld:
    image: ivct/helloworld:pi-skeleton-${TS_HW_VERSION}
    network_mode: host
    environment:
    - SETTINGS_DESIGNATOR=${SETTINGS_DESIGNATOR}
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/lrc/code
