version: '3.7'
# ==============================================================================
# The HelloWorld SUT
# ==============================================================================

services:
# The HW application.
  helloworld:
    image: ivct/helloworld:ma-${HW_VERSION}
    environment:
    - SETTINGS_DESIGNATOR=(setqb RTI_tcpPort 4000) (setqb RTI_tcpForwarderAddr "rtiexec")
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
    networks:
    - sutnet

networks:
  sutnet:
    driver: bridge
    name: mysimnetwork
