version: '3.7'
# ==============================================================================
# The VTMaK RTIExec composition.
# ==============================================================================

services:
# Start the X Server.
# To connect, navigate to http://$DOCKERHOST:8181/vnc.html
  xserver:
    image: hlacontainers/xserver
    ports:
    - "8181:8080"
    networks:
    - sutnet

# Start the VTMaK RTI Exec
# and mount the RTI from the host file system.
  rtiexec:
    image: hlacontainers/vtmak-rtiexec:skeleton
    environment:
    - DISPLAY=xserver:0
    volumes:
    - ${VTMAK_RTI_HOME}:/usr/local/makRti
    networks:
    - sutnet

networks:
  sutnet:
    driver: bridge
    name: mysimnetwork
