version: '3.7'
# ==============================================================================
# The VTMaK RTIExec composition.
# ==============================================================================

services:
# Start the X Server.
# To connect, navigate to http://$DOCKERHOST:8181/vnc.html
  xserver:
    image: hlacontainers/xserver
    ports:
    - "8181:8080"
    networks:
    - sutnet

# Start the VTMaK RTI Exec
  rtiexec:
    image: hlacontainers/vtmak-rtiexec:${VTMAK_VERSION}
    environment:
    - DISPLAY=xserver:0
    networks:
    - sutnet

networks:
  sutnet:
    driver: bridge
    name: mysimnetwork
