version: '3.7'
# ==============================================================================
# The HelloWorld SUT
# ==============================================================================

services:
# The HW application.
# The LRC is mounted from the host file system.
  helloworld:
    image: ivct/helloworld:ma-skeleton-${HW_VERSION}
    environment:
    - SETTINGS_DESIGNATOR=(setqb RTI_tcpPort 4000) (setqb RTI_tcpForwarderAddr "rtiexec")
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
    volumes:
    - ${VTMAK_RTI_HOME}:/usr/local/lrc/code
    networks:
    - sutnet

networks:
  sutnet:
    driver: bridge
    name: mysimnetwork
