version: '3'
# ==============================================================================
# IVCT composition using Pitch Booster to connect to the SUT.
# ==============================================================================

services:
# ==============================================================================
# Pitch Child Booster
# ==============================================================================
  childbooster:
    image: app-docker136.hex.tno.nl/pitch/booster:2.3.0
    mac_address: ${BOOSTER_MAC_ADDRESS}
    command: -v
    ports:
    - "8623:8623"
    environment:
    - ISCHILD=
    - PARENTID=${PARENTID}
    - PARENTNAME=${PARENTNAME}
    - PARENTADDRESS=${BOOSTER_PARENTADDRESS}
    - CHILDID=${CHILDID}
    - CHILDNAME=${CHILDNAME}
    volumes:
    - booster_license_volume:/usr/local/PitchBooster/jre/.systemPrefs/se/pitch/booster/config:nocopy
    depends_on:
    - booster_license

  booster_license:
    image: ${BOOSTER_LICENSE_IMAGE}
    volumes:
    - booster_license_volume:/data

# ==============================================================================
# Pitch web UI container
# This image provides a web UI to the CRC.
# URL: ${DOCKERHOST}:${WEBUI_PORT}
# Login: admin / admin
# ==============================================================================
  webui:
    image: app-docker136.hex.tno.nl/pitch/web:2.3.0
    ports:
    - "${WEBUI_PORT}:8080"

# ==============================================================================
# Apache Active Message Queue
# The MQ is used for communication between the different IVCT components.
# ==============================================================================
  activemq:
    image: rmohr/activemq:5.14.5-alpine

# ==============================================================================
# IVCT Test Case Runner
# The TC Runner is an HLA federate application based on an LRC base image.
# ==============================================================================
  tc-runner:
    image: msg134/tc-runner:pi-development-latest
    depends_on:
    - activemq
    - runtime-config
    - ts-hla-encoding-rules-tester
    volumes:
    - runtime-config:/root/conf:nocopy
    - ts-hla-encoding-rules-tester:/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/
      LRC_MASTERADDRESS: childbooster:8688
      PITCH_CRCADDRESS: ${PITCH_CRCNAME}@childbooster:8688
      
# ==============================================================================
# IVCT Logsink component
# ==============================================================================
  logsink:
    image: msg134/logsink:development-latest
    depends_on:
    - activemq
    - runtime-config
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/

# ==============================================================================
# IVCT GUI component
# URL: ${DOCKERHOST}:${IVCTUI_PORT}/ivct.gui.ui.html
# Login: admin / admin
# ==============================================================================
  gui:
    image: msg134/ivct-gui:development-latest
    depends_on:
    - activemq
    - runtime-config
    ports:
    - "${IVCTUI_PORT}:8080"
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/

# ==============================================================================
# IVCT runtime configuration data
# ==============================================================================
  runtime-config:
    image: msg134/runtime-config:development-latest
    volumes:
    - runtime-config:/root/conf

# ==============================================================================
# IVCT Test Suite data for Encoding Rules
# ==============================================================================
  ts-hla-encoding-rules-tester:
    image: msg134/ts-hla-encoding-rules-tester:development-1.0.1
    volumes:
    - ts-hla-encoding-rules-tester:/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1

# ==============================================================================
# Data volumes for Test Suites and Licenses
# ==============================================================================
volumes:
  runtime-config:
  ts-hla-encoding-rules-tester:
  booster_license_volume:
