version: '3.7'
# ==============================================================================
# The HelloWorld SUT.
# ==============================================================================

services:
  helloworld:
    image: ivct/helloworld:po-${HW_VERSION}
    network_mode: host
    environment:
    - PORTICO_LRCADAPTER=eth0
    - PORTICO_JGROUPS_UDP_ADDRESS=224.1.0.1
    - PORTICO_JGROUPS_UDP_PORT=6666
    - SETTINGS_DESIGNATOR=
    - FEDERATE_NAME=A
    - POPULATION_SIZE=100
    - CYCLES=1000000
