version: '3'
# ==============================================================================
# SHIPSIM IVCT composition for the Pitch RTI
#
# This composition consists of various container images to test the SHIPSIM
# federate application.
#
# In this composition the Pitch CRC is started with a license container.
# The license key in the license container is tight to a Pitch license agreement
# and must remain proprietary to the licensee. Therefore the license container
# cannot be stored in the MSaaS Docker Registry. The license container image is
# defined by an environment variable.
# ==============================================================================

services:
# ==============================================================================
# Pitch CRC
# The MAC_ADDRESS is required and the value relates to the license key in the
# licenses container.
# ==============================================================================
  crc:
    image: app-docker136.hex.tno.nl/pitch/crc:5.4.0.0
    depends_on:
    - license
    mac_address: ${MAC_ADDRESS}
    environment:
      CRC_REJECT_MISMATCHED_VERSIONS: "false"
      CRC_SKIP_CONNECTIVITY_CHECK: "true"
    volumes:
    - license_volume:/etc/.java/.systemPrefs/se/pitch/prti1516e/config:nocopy

# ==============================================================================
# Pitch CRC license container
# The provided image contains the license key.
# ==============================================================================
  license:
    image: ${LICENSE_IMAGE}
    volumes:
    - license_volume:/license-key

# ==============================================================================
# Pitch web UI container
# This image provides a web UI to the CRC.
# URL: ${DOCKERHOST}:${WEBUI_PORT}
# Login: admin / admin
# ==============================================================================
  webui:
    image: app-docker136.hex.tno.nl/pitch/web:2.3.0
    ports:
    - "${WEBUI_PORT}:8080"

# ==============================================================================
# Apache Active Message Queue
# The MQ is used for communication between the different IVCT components.
# ==============================================================================
  activemq:
    image: rmohr/activemq:5.14.5-alpine

# ==============================================================================
# IVCT Test Case Runner
# The TC Runner is an HLA federate application based on an LRC base image.
# ==============================================================================
  tc-runner:
    image: msg134/tc-runner:pi-development-latest
    depends_on:
    - activemq
    - runtime-config
    - ts-hla-encoding-rules-tester
    volumes:
    - runtime-config:/root/conf:nocopy
    - ts-hla-encoding-rules-tester:/root/conf/TestSuites/TS_HLA_EncodingRulesTester-1.0.1:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/

# ==============================================================================
# IVCT Logsink component
# ==============================================================================
  logsink:
    image: msg134/logsink:development-latest
    depends_on:
    - activemq
    - runtime-config
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/

# ==============================================================================
# IVCT GUI component
# URL: ${DOCKERHOST}:${IVCTUI_PORT}/ivct.gui.ui.html
# Login: admin / admin
# ==============================================================================
  gui:
    image: msg134/ivct-gui:development-latest
    depends_on:
    - activemq
    - runtime-config
    ports:
    - "${IVCTUI_PORT}:8080"
    volumes:
    - runtime-config:/root/conf:nocopy
    environment:
      ACTIVEMQ_HOST: activemq
      ACTIVEMQ_PORT: 61616
      IVCT_CONF: /root/conf/

# ==============================================================================
# IVCT runtime configuration data
# ==============================================================================
  runtime-config:
    image: msg134/runtime-config:development-latest
    volumes:
    - runtime-config:/root/conf

# ==============================================================================
# IVCT Test Suite data for Encoding Rules
# ==============================================================================
  ts-hla-encoding-rules-tester:
    image: msg134/ts-hla-encoding-rules-tester:1.0.1
    volumes:
    - ts-hla-encoding-rules-tester:/root/conf/TestSuites/TS_HLA_EncodingRulesTester

# ==============================================================================
# The SUT components follow below
# ==============================================================================
  shipsim:
    image: app-docker136.hex.tno.nl/msaas-aus/shipsim:pi
    environment:
    - FEDERATENAME=VRF/UG
    - LRC_MASTERADDRESS=crc:8989
    depends_on:
    - crc

# ==============================================================================
# Data volumes for Test Suites and Licenses
# ==============================================================================
volumes:
  runtime-config:
  ts-hla-encoding-rules-tester:
  license_volume:
