version: '3'
# ==============================================================================
# The HelloWorld SUT.
# ==============================================================================

services:
  helloworld:
    image: ivct/helloworld:${TS_HW_VERSION}
    network_mode: host
    environment:
    - SETTINGS_DESIGNATOR=
    - FEDERATE_NAME=A
    - POPULATION_SIZE=100
    - CYCLES=1000000
