apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: ivct-docker.iosb.fraunhofer.de
    path: "/opt/nfs-freigabe"
  mountOptions:
    - nfsvers=4.2
