---
apiVersion: v1
kind: Service
metadata:
  name: activemqsrvc
  labels:
    app: activemq
spec:
  type: NodePort
  ports:
    - name: "61616"
      port: 61616
      #targetPort: 61616
    - name: "8161"
      port: 8161
      #targetPort: 8161
  selector:
    app: activemq
