version: '3'
# ==============================================================================
# The HelloWorld SUT.
# ==============================================================================

services:
# Start the Hello World federate
  helloworld:
    image: ivct/helloworld:pi-skeleton-${HW_VERSION}
    network_mode: host
    environment:
    - SETTINGS_DESIGNATOR=crcAddress=localhost:8989
    - FEDERATE_NAME=A
    - POPULATION=100
    - CYCLES=1000000
    volumes:
    - ${PITCH_RTI_HOME}:/usr/local/lrc/code
